using Newtonsoft.Json;
using System;
using System.IO;

namespace ProcesioSDK.Dto.Data
{
    public class FileContent
    {
        /// <summary>
        /// File content
        /// </summary>
        [JsonIgnore]
        public Stream Data { get; set; }

        /// <summary>
        /// File name with extension
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// File id generated by procesio platform
        /// </summary>
        [JsonProperty("id")]
        public Guid FileId { get; set; }
    }
}
