name: .NET Core

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.DEPLOY_KEY }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.DEPLOY_KEY}}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Debug SDKProcesio/SDKProcesio.csproj --output ./work/Debug
    - name: Publish
      run: dotnet nuget push ./work/Debug/*.nupkg -k ${{secrets.DEPLOY_KEY}} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate -n true
      env:
       GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
